# "window.opacity" = 1.0

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
import = ["/home/pedro/.config/alacritty/catppuccin-mocha.toml", "/home/pedro/.config/alacritty/fonts.toml"]

